AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  # Ignore challenges already completed to make report cleaner
  Exclude:
    - 'lib/bauk/advent_of_code/year_2022/challenge_0[1-3]/'
    - 'lib/bauk/advent_of_code/year_2022/challenge_2[3-4]/*.rb'

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 165

Metrics/MethodLength:
  Max: 25

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Metrics/ClassLength:
  Max: 200

Style/PerlBackrefs:
  Enabled: false # Allows usage of $1 and $2 for regex groups
