AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  # Ignore challenges already completed to make report cleaner
  Exclude:
    - 'lib/bauk/advent_of_code/year_2022/challenge_0[1-3]/'
    - 'lib/bauk/advent_of_code/year_2022/challenge_2[3-4]/*.rb'

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 165

Metrics/MethodLength:
  Max: 50 # For now, as these challenges have some dirty quick hacks (e.g. large hash data in code)

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 20

Metrics/ClassLength:
  Max: 200

Metrics/AbcSize:
  Max: 20

Style/PerlBackrefs:
  Enabled: false # Allows usage of $1 and $2 for regex groups
