module Advent
  module Of
    module Code
      module 2022
        module 24
          VERSION: String
          # See the writing guide of rbs: https://github.com/ruby/rbs#guides
        end
      end
    end
  end
end
